package juan.marin.lopez.examendi1224;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.apache.poi.sl.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author ADMINISTRADORGS2
 */
public class ExamenDI1224JuanMarin extends javax.swing.JPanel {

    String[] clase1 = {"Juan", "Burumn", "Pipu", "Lara"};
    String[] clase2 = {"Jaime", "Bruena", "Pipuna", "Agustin"};
    
    /**
     * Creates new form ExamenDI1224JuanMarin
     */
    public ExamenDI1224JuanMarin() {
        initComponents();
        jComboBoxClase.addActionListener(e -> actualizarAlumnos());
        
        // Llena el JComboBox con los equipos
        jComboBoxClase.addItem("Clase_A");
        jComboBoxClase.addItem("Clase_B");
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jComboBoxClase = new javax.swing.JComboBox<>();
        jComboBoxAlumno = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        componente1 = new juan.marin.lopez.examendi1224.Componente();
        componente2 = new juan.marin.lopez.examendi1224.Componente();
        componente3 = new juan.marin.lopez.examendi1224.Componente();
        componente4 = new juan.marin.lopez.examendi1224.Componente();

        setLayout(new java.awt.GridBagLayout());

        jComboBoxClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(jComboBoxClase, gridBagConstraints);

        jComboBoxAlumno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(jComboBoxAlumno, gridBagConstraints);

        jLabel1.setText("Mates");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(jLabel1, gridBagConstraints);

        jLabel2.setText("Lengua");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(jLabel2, gridBagConstraints);

        jLabel3.setText("Física");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(jLabel3, gridBagConstraints);

        jLabel4.setText("Química");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(jLabel4, gridBagConstraints);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        add(jButton1, gridBagConstraints);

        jButton2.setText("Resetear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        add(jButton2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(componente1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(componente2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(componente3, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 15, 15, 15);
        add(componente4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String mates2 = (String) componente1.getText();
        int mates = Integer.parseInt(mates2);
        String lengua2 = (String) componente2.getText();
        int lengua = Integer.parseInt(lengua2);
        String fisica2 = (String) componente3.getText();
        int fisica = Integer.parseInt(fisica2);
        String quimica2 = (String) componente4.getText();
        int quimica = Integer.parseInt(quimica2);
        try {
            String nombre = (String) jComboBoxAlumno.getSelectedItem();
            String filePath = jComboBoxClase.getSelectedItem() + "_" + nombre + ".xlsx";
            File archivo = new File(filePath);
            Workbook wb;
            org.apache.poi.ss.usermodel.Sheet sheet;

            if (archivo.exists()) {
                // Si el archivo existe, abrirlo
                FileInputStream fis = new FileInputStream(archivo);
                wb = new XSSFWorkbook(fis);
                sheet = wb.getSheetAt(0);
                fis.close();
            } else {
                // Si no existe, crearlo desde cero
                wb = new XSSFWorkbook();
                sheet = wb.createSheet("Estadísticas");

                // Crear las cabeceras (agregar FG%, eFG%, Tiros Totales)
                Row cabecera = sheet.createRow(0);
                cabecera.createCell(0).setCellValue("Nombre Alumno");
                cabecera.createCell(1).setCellValue("Mates");
                cabecera.createCell(2).setCellValue("Lengua");
                cabecera.createCell(3).setCellValue("Física");
                cabecera.createCell(4).setCellValue("Química");
            }

                
                // Crear una nueva fila para el nuevo jugador en la primera fila libre
            Row row = sheet.createRow(1);
            row.createCell(0).setCellValue(nombre);
            row.createCell(1).setCellValue(mates);  // Agregar Tiros Totales Realizados
            row.createCell(2).setCellValue(lengua);
            row.createCell(3).setCellValue(fisica);
            row.createCell(4).setCellValue(quimica);
            
            FileOutputStream fos = new FileOutputStream(archivo);
            wb.write(fos);
            fos.close();
        } catch (IOException e) {
            e.printStackTrace();
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        componente1.setText("1");
        componente2.setText("1");
        componente3.setText("1");
        componente4.setText("1");
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void actualizarAlumnos() {
        String equipoSeleccionado = (String) jComboBoxClase.getSelectedItem();

        jComboBoxAlumno.removeAllItems();  // Limpia el JComboBox de jugadores

        if (equipoSeleccionado.equals("Clase_A")) {
            // Agrega jugadores del equipo Los Ángeles Lakers
            for (String jugador : clase1) {
                jComboBoxAlumno.addItem(jugador);
            }
        } else if (equipoSeleccionado.equals("Clase_B")) {
            // Agrega jugadores del equipo Golden State Warriors
            for (String jugador : clase2) {
                jComboBoxAlumno.addItem(jugador);
            }
        }
    }

    public static void main(String args[]) {
        JFrame interfaz = new JFrame("Interfaz");
        ExamenDI1224JuanMarin panel = new ExamenDI1224JuanMarin();
        interfaz.setContentPane(panel);
        interfaz.setSize(300, 400);
        interfaz.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        interfaz.setLocationRelativeTo(null);
        interfaz.setVisible(true);
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private juan.marin.lopez.examendi1224.Componente componente1;
    private juan.marin.lopez.examendi1224.Componente componente2;
    private juan.marin.lopez.examendi1224.Componente componente3;
    private juan.marin.lopez.examendi1224.Componente componente4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxAlumno;
    private javax.swing.JComboBox<String> jComboBoxClase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
